version: '2'

services:
  consul_master:
    build: .
    container_name: consul_master
    restart: always
    tty: true
    ports:
      - "8080:80"
      - "8500:8500"
    volumes: 
      - ./conf/nginx-master/default.conf:/etc/nginx/conf.d/default.conf
    networks: 
      - consul-network

  service1:
    build: .
    container_name: service1
    restart: always
    tty: true
    ports:
      - "8081:80"
    volumes: 
      - ./services/service1:/usr/share/nginx/html/
      - ./conf/service:/etc/consul.d
    networks: 
      - consul-network

  service2:
    build: .
    container_name: service2
    restart: always
    tty: true
    ports:
      - "8082:80"
    volumes: 
      - ./services/service2:/usr/share/nginx/html/
      - ./conf/service:/etc/consul.d
    networks: 
      - consul-network

networks: 
  consul-network:
    driver: bridge